name: Docker Compose Actions Workflow

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start containers
      run: docker compose -f "./app/docker-compose.yml" up -d --build